/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class", // darkmode
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        // All colours now point to CSS variables (defined in index.css)
        ink: "var(--ink)",
        void: "var(--void)",
        fog: "var(--fog)",
        smudge: "var(--smudge)",
        ash: "var(--ash)",
        bone: "var(--bone)",
        paper: "var(--paper)",
        lav: "var(--lav)",
        blush: "var(--blush)",
        sage: "var(--sage)",
        sky: "var(--sky)",
      },
      fontFamily: {
        display: ["'IM Fell English'", "Georgia", "'Times New Roman'", "serif"],
        title: ["'Special Elite'", "'Courier New'", "monospace"],
        serif: ["'Crimson Pro'", "Georgia", "'Times New Roman'", "serif"],
        body: ["'Crimson Pro'", "Georgia", "'Times New Roman'", "serif"],
        mono: ["'Space Mono'", "'Courier New'", "monospace"],
      },
      fontSize: {
        hero: ["clamp(3.5rem, 9vw, 7.5rem)", { lineHeight: "1.05", letterSpacing: "-0.01em" }],
        section: ["clamp(2.2rem, 5vw, 4.5rem)", { lineHeight: "1.1" }],
        display: ["clamp(1.6rem, 3vw, 2.4rem)", { lineHeight: "1.2" }],
        "2xs": ["0.58rem", { lineHeight: "1.5" }],
        "xs-mono": ["0.62rem", { lineHeight: "1.6" }],
        "sm-serif": ["0.88rem", { lineHeight: "1.7" }],
      },
      letterSpacing: {
        "widest-2": "0.14em",
        "widest-3": "0.2em",
      },
      lineHeight: {
        "relaxed-serif": "1.85",
        "tight-display": "1.05",
      },
      spacing: {
        section: "clamp(3rem, 8vh, 7rem)",
        "18": "4.5rem",
        "22": "5.5rem",
        "26": "6.5rem",
        "30": "7.5rem",
        "88": "22rem",
        "92": "23rem",
        "100": "25rem",
        "112": "28rem",
        "128": "32rem",
      },
      maxWidth: {
        container: "72rem",
        "prose-xl": "72ch",
        "prose-lg": "60ch",
        "prose-md": "48ch",
        "prose-sm": "38ch",
      },
      borderRadius: {
        none: "0px",
        px: "1px",
        sm: "2px",
        md: "4px",
        lg: "8px",
        xl: "12px",
        DEFAULT: "2px",
      },
      borderWidth: {
        DEFAULT: "1px",
        "0": "0",
        "2": "2px",
        half: "0.5px",
      },
      boxShadow: {
        "lift-sm": "0 4px 16px rgba(26,26,26,0.06)",
        lift: "0 10px 40px rgba(26,26,26,0.09)",
        "lift-lg": "0 20px 60px rgba(26,26,26,0.12)",
        ink: "0 2px 8px rgba(26,26,26,0.04)",
        none: "none",
      },
      keyframes: {
        "fade-up": {
          "0%": { opacity: "0", transform: "translateY(14px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "dream-flash": {
          "0%": { opacity: "0", filter: "brightness(4)" },
          "100%": { opacity: "1", filter: "brightness(1)" },
        },
        "draw-line": {
          "0%": { transform: "scaleX(0)", transformOrigin: "left" },
          "100%": { transform: "scaleX(1)", transformOrigin: "left" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px) rotate(var(--card-rotate, 0deg))" },
          "50%": { transform: "translateY(-6px) rotate(var(--card-rotate, 0deg))" },
        },
        "ink-bloom": {
          "0%": { boxShadow: "0 1.5px 0 0 rgba(26,26,26,0)" },
          "100%": { boxShadow: "0 1.5px 0 0 rgba(26,26,26,0.2)" },
        },
        "stagger-in": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-up": "fade-up 0.7s cubic-bezier(0.25,0.1,0.25,1) both",
        "dream-flash": "dream-flash 0.9s cubic-bezier(0.25,0.1,0.25,1) both",
        "draw-line": "draw-line 0.4s cubic-bezier(0.25,0.1,0.25,1) both",
        float: "float 5s ease-in-out infinite",
        "float-slow": "float 8s ease-in-out infinite",
        "ink-bloom": "ink-bloom 0.5s ease forwards",
        "stagger-in": "stagger-in 0.6s cubic-bezier(0.25,0.1,0.25,1) both",
      },
      transitionTimingFunction: {
        dream: "cubic-bezier(0.25, 0.1, 0.25, 1)",
        "in-slow": "cubic-bezier(0.4, 0, 1, 1)",
        "out-slow": "cubic-bezier(0, 0, 0.2, 1)",
        pencil: "cubic-bezier(0.0, 0.0, 0.2, 1)",
      },
      transitionDuration: {
        "350": "350ms",
        "450": "450ms",
        "600": "600ms",
        "800": "800ms",
        "900": "900ms",
      },
      backdropBlur: {
        xs: "2px",
        sm: "4px",
      },
      aspectRatio: {
        "3/4": "3 / 4",
        "4/3": "4 / 3",
        "1/1": "1 / 1",
        "16/9": "16 / 9",
      },
      gridTemplateColumns: {
        timeline: "88px 1fr",
        portrait: "1fr 380px",
        contact: "1fr 1fr",
        "fill-240": "repeat(auto-fill, minmax(240px, 1fr))",
        "fill-300": "repeat(auto-fill, minmax(300px, 1fr))",
      },
      zIndex: {
        nav: "50",
        overlay: "40",
        card: "10",
        base: "1",
      },
      screens: {
        xs: "380px",
        sm: "640px",
        md: "768px",
        lg: "1024px",
        xl: "1280px",
        "2xl": "1536px",
      },
    },
  },
  plugins: [],
};